[tool.poetry]
name = "bookops-marc"
version = "0.1.0"
description = ""
authors = ["Tomek <klingaroo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pymarc = "^4.1.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-cov = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
    /(
        \.eggs
       | \.git
       | \.hg
       | \.mypy_cache
       | \.tox
       | \.venv
       | _build
       | buck-out
       | build
       | dist
    )/
    | temp.py
)
'''
