[tool.poetry]
name = "bookops-marc"
version = "0.8.0"
license = "MIT"
description = "A sweetened `pymarc.Record` module for extraction of data from local Sierra records."
authors = ["Tomek <klingaroo@gmail.com>"]
readme = "README.md"
keywords = ["cataloging", "bibliographic records", "MARC"]

[tool.poetry.dependencies]
python = "^3.7"
pymarc = "^4.1.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
black = "^22.1.0"
mypy = "^0.942"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
(
    /(
        \.eggs
       | \.git
       | \.hg
       | \.mypy_cache
       | \.tox
       | \.venv
       | _build
       | buck-out
       | build
       | dist
    )/
    | temp.py
)
'''
